/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AiUsageMetricService } from "../aiUsageMetric.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AiUsageMetricCreateInput } from "./AiUsageMetricCreateInput";
import { AiUsageMetric } from "./AiUsageMetric";
import { AiUsageMetricFindManyArgs } from "./AiUsageMetricFindManyArgs";
import { AiUsageMetricWhereUniqueInput } from "./AiUsageMetricWhereUniqueInput";
import { AiUsageMetricUpdateInput } from "./AiUsageMetricUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AiUsageMetricControllerBase {
  constructor(
    protected readonly service: AiUsageMetricService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AiUsageMetric })
  @nestAccessControl.UseRoles({
    resource: "AiUsageMetric",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAiUsageMetric(
    @common.Body() data: AiUsageMetricCreateInput
  ): Promise<AiUsageMetric> {
    return await this.service.createAiUsageMetric({
      data: {
        ...data,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,

        service: data.service
          ? {
              connect: data.service,
            }
          : undefined,
      },
      select: {
        client: {
          select: {
            id: true,
          },
        },

        cost: true,
        createdAt: true,
        id: true,
        messageCount: true,

        service: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        tokenConsumption: true,
        updatedAt: true,
        usageDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AiUsageMetric] })
  @ApiNestedQuery(AiUsageMetricFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AiUsageMetric",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiUsageMetrics(
    @common.Req() request: Request
  ): Promise<AiUsageMetric[]> {
    const args = plainToClass(AiUsageMetricFindManyArgs, request.query);
    return this.service.aiUsageMetrics({
      ...args,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        cost: true,
        createdAt: true,
        id: true,
        messageCount: true,

        service: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        tokenConsumption: true,
        updatedAt: true,
        usageDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AiUsageMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiUsageMetric",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async aiUsageMetric(
    @common.Param() params: AiUsageMetricWhereUniqueInput
  ): Promise<AiUsageMetric | null> {
    const result = await this.service.aiUsageMetric({
      where: params,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        cost: true,
        createdAt: true,
        id: true,
        messageCount: true,

        service: {
          select: {
            id: true,
          },
        },

        serviceType: true,
        tokenConsumption: true,
        updatedAt: true,
        usageDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AiUsageMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiUsageMetric",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAiUsageMetric(
    @common.Param() params: AiUsageMetricWhereUniqueInput,
    @common.Body() data: AiUsageMetricUpdateInput
  ): Promise<AiUsageMetric | null> {
    try {
      return await this.service.updateAiUsageMetric({
        where: params,
        data: {
          ...data,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,

          service: data.service
            ? {
                connect: data.service,
              }
            : undefined,
        },
        select: {
          client: {
            select: {
              id: true,
            },
          },

          cost: true,
          createdAt: true,
          id: true,
          messageCount: true,

          service: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          tokenConsumption: true,
          updatedAt: true,
          usageDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AiUsageMetric })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AiUsageMetric",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAiUsageMetric(
    @common.Param() params: AiUsageMetricWhereUniqueInput
  ): Promise<AiUsageMetric | null> {
    try {
      return await this.service.deleteAiUsageMetric({
        where: params,
        select: {
          client: {
            select: {
              id: true,
            },
          },

          cost: true,
          createdAt: true,
          id: true,
          messageCount: true,

          service: {
            select: {
              id: true,
            },
          },

          serviceType: true,
          tokenConsumption: true,
          updatedAt: true,
          usageDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
