/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Service,
  AiUsageMetric as PrismaAiUsageMetric,
  Client as PrismaClient,
  Invoice as PrismaInvoice,
  Project as PrismaProject,
} from "@prisma/client";

export class ServiceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ServiceCountArgs, "select">): Promise<number> {
    return this.prisma.service.count(args);
  }

  async services(args: Prisma.ServiceFindManyArgs): Promise<Service[]> {
    return this.prisma.service.findMany(args);
  }
  async service(
    args: Prisma.ServiceFindUniqueArgs
  ): Promise<Service | null> {
    return this.prisma.service.findUnique(args);
  }
  async createService(args: Prisma.ServiceCreateArgs): Promise<Service> {
    return this.prisma.service.create(args);
  }
  async updateService(args: Prisma.ServiceUpdateArgs): Promise<Service> {
    return this.prisma.service.update(args);
  }
  async deleteService(args: Prisma.ServiceDeleteArgs): Promise<Service> {
    return this.prisma.service.delete(args);
  }

  async findAiUsageMetrics(
    parentId: string,
    args: Prisma.AiUsageMetricFindManyArgs
  ): Promise<PrismaAiUsageMetric[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .aiUsageMetrics(args);
  }

  async findClients(
    parentId: string,
    args: Prisma.ClientFindManyArgs
  ): Promise<PrismaClient[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .clients(args);
  }

  async findInvoices(
    parentId: string,
    args: Prisma.InvoiceFindManyArgs
  ): Promise<PrismaInvoice[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invoices(args);
  }

  async findProjects(
    parentId: string,
    args: Prisma.ProjectFindManyArgs
  ): Promise<PrismaProject[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .projects(args);
  }
}
